export type ServiceItem = {
  slug: string;
  title: string;
  short: string;
  description: string;
  price: string;
  priceMin: number;
  priceMax: number;
  hours: string;
  image: string;
  category: string;
  details?: string[];
  isPartsOrder?: boolean;
};

// Нормогодина: 120–200 грн
export const HOUR_RATE_MIN = 120;
export const HOUR_RATE_MAX = 200;

export const services: ServiceItem[] = [
  {
    slug: "zamovlennya-detaley",
    title: "Замовлення запчастин через нашу фірму",
    short: "Підбір та доставка оригінальних і якісних аналогів запчастин для вантажного транспорту без зайвих клопотів.",
    description:
      "Замовте потрібні запчастини через нашу фірму — підберемо оригінал або перевірений аналог, організуємо доставку. Ви залишаєте заявку, ми займаємось пошуком і логістикою.",
    price: "За запитом",
    priceMin: 0,
    priceMax: 0,
    hours: "1–5 днів",
    image: "https://images.unsplash.com/photo-1581092335878-2d9ff86ca2bf?w=800&auto=format&fit=crop",
    category: "Запчастини",
    details: [
      "Оригінальні та перевірені аналоги",
      "Підбір за VIN або артикулом",
      "Доставка по Україні",
      "Гарантія на деталі",
    ],
    isPartsOrder: true,
  },
  {
    slug: "remont-prychipnoji-tehniky",
    title: "ТО та ремонт причепів і напівпричепів",
    short: "Обслуговування причіпної техніки та ремонт осьових агрегатів BPW, SAF, ROR.",
    description:
      "Сервісна станція виконує технічне обслуговування, ремонт причепів і напівпричепів, а також ремонт осьових агрегатів BPW, SAF, ROR, SMB, TRA та FRU для вантажного транспорту.",
    price: "від 960 грн",
    priceMin: 960,
    priceMax: 4000,
    hours: "8–20 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/84f9033f2f5efc24deda487fb7122d243f40e055.jpg",
    category: "Причіпна техніка",
    details: ["Осьові агрегати BPW, SAF, ROR", "SMB, TRA та FRU", "Повна дефектація перед ремонтом", "Перевірка рами та несучих елементів"],
  },
  {
    slug: "beral",
    title: "Наклепка гальмівних накладок BERAL",
    short: "Професійна наклепка гальмівних накладок на спеціалізованому стенді BERAL.",
    description:
      "Проводимо наклепку гальмівних накладок на стенді BERAL для вантажних автомобілів, причепів і напівпричепів з дотриманням технології відновлення.",
    price: "від 480 грн",
    priceMin: 480,
    priceMax: 1200,
    hours: "4–6 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/4b96506b9c1e24cef4e01a1a1bc5f506be36f486.jpg",
    category: "Гальмівна система",
    details: ["Стенд BERAL", "Усі марки вантажних авто", "Дотримання заводської технології", "Контроль якості після наклепки"],
  },
  {
    slug: "remont-galmivnyh-mehanizmiv",
    title: "Ремонт гальмівних механізмів і супортів KNORR",
    short: "Ремонт супортів і гальмівних механізмів спецінструментом KNORR.",
    description:
      "Виконуємо ремонт гальмівних механізмів супортів із використанням спеціального інструменту KNORR для точного та безпечного відновлення вузлів.",
    price: "від 360 грн",
    priceMin: 360,
    priceMax: 1400,
    hours: "3–7 год",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop",
    category: "Гальмівна система",
    details: ["Оригінальний інструмент KNORR", "Точне відновлення супортів", "Заміна зношених ущільнень", "Перевірка після ремонту"],
  },
  {
    slug: "zamina-povorotnyh-shkvorniv",
    title: "Заміна поворотних шкворнів вантажних автомобілів",
    short: "Заміна шкворнів пресом Fuchs Hydraulik без пошкодження вузлів.",
    description:
      "Проводимо заміну поворотних шкворнів вантажних автомобілів із використанням преса Fuchs Hydraulik, що дозволяє виконати роботи точно та безпечно.",
    price: "від 480 грн",
    priceMin: 480,
    priceMax: 1600,
    hours: "4–8 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/7bc67c17dd5214fc636d2874e1fcee6a486a3f5b.jpg",
    category: "Ходова частина",
    details: ["Прес Fuchs Hydraulik", "Точне пресування без пошкоджень", "Усі марки вантажних авто", "Рекомендована заміна щоразу при ремонті"],
  },
  {
    slug: "zamina-masla",
    title: "Заміна масла в двигунах і трансмісії",
    short: "Заміна мастил згідно рекомендацій виробника з контролем рівнів.",
    description:
      "Виконуємо заміну масла в двигунах і трансмісії вантажних автомобілів відповідно до регламенту та рекомендацій заводів-виробників.",
    price: "від 240 грн",
    priceMin: 240,
    priceMax: 600,
    hours: "2–3 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/c2a33e08240f6e17925d6636ea99aebbd0d47aff.jpg",
    category: "Технічне обслуговування",
    details: ["Згідно регламенту виробника", "Оригінальні та перевірені аналоги", "Заміна фільтрів", "Контроль рівнів після заміни"],
  },
  {
    slug: "remont-forsunok-common-rail",
    title: "Діагностика та ремонт форсунок Common Rail",
    short: "Стендова перевірка, ультразвукове очищення та відновлення форсунок.",
    description:
      "Проводимо діагностику та ремонт форсунок системи Common Rail для стабільної роботи двигуна, правильної подачі палива та надійної експлуатації авто.",
    price: "від 600 грн",
    priceMin: 600,
    priceMax: 2400,
    hours: "5–12 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/8daee9beb5e07ab91c97ad77d6dc174ce24ecbc7.jpg",
    category: "Паливна система",
    details: ["Стендова перевірка форсунок", "Ультразвукове очищення", "Відновлення розпилювачів", "Перевірка тиску в рейці"],
  },
  {
    slug: "remont-dviguniv",
    title: "Ремонт двигунів",
    short: "Капітальний і частковий ремонт двигунів вантажних автомобілів.",
    description:
      "Виконуємо діагностику та ремонт двигунів вантажних автомобілів, визначаємо причину несправності та підбираємо оптимальне рішення для відновлення роботи.",
    price: "від 1800 грн",
    priceMin: 1800,
    priceMax: 9000,
    hours: "15–45 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/4b7ff1d1e9c7337632543ebc2f5e043734922980.jpg",
    category: "Двигун",
    details: ["Капітальний і частковий ремонт", "Діагностика компресії", "Заміна ГБЦ, прокладок", "Налаштування ГРМ"],
  },
  {
    slug: "remont-kpp",
    title: "Ремонт КПП",
    short: "Діагностика та ремонт механічних і автоматичних КПП.",
    description:
      "Проводимо діагностику та ремонт КПП вантажних автомобілів з урахуванням технічного стану вузла та характеру поломки.",
    price: "від 1200 грн",
    priceMin: 1200,
    priceMax: 6000,
    hours: "10–30 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/9e5670c83836bb4d566263a45cbe465a73ddb034.jpg",
    category: "Трансмісія",
    details: ["Механічні та автоматичні КПП", "Заміна синхронізаторів", "Ремонт підшипників", "Регулювання перемикання"],
  },
  {
    slug: "differential",
    title: "Ремонт редукторів і ведучих мостів",
    short: "Дефектування та ремонт редукторів, регулювання зазорів.",
    description:
      "Виконуємо діагностику, дефектування та ремонт редукторів вантажних автомобілів і причіпної техніки.",
    price: "від 2000 грн",
    priceMin: 2000,
    priceMax: 10000,
    hours: "16–50 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/98afea8526d7957b5b407040e0373b0e62216e98.jpg",
    category: "Трансмісія",
    details: ["Ведучі мости всіх марок", "Заміна шестерень і підшипників", "Регулювання зазорів", "Контрольна обкатка після ремонту"],
  },
  {
    slug: "remont-pidvisky",
    title: "Ремонт підвіски вантажних автомобілів",
    short: "Листові та пневматичні підвіски — діагностика, ремонт, регулювання.",
    description:
      "Проводимо ремонт підвіски вантажних автомобілів для безпечної, стабільної та комфортної експлуатації транспорту.",
    price: "від 480 грн",
    priceMin: 480,
    priceMax: 3200,
    hours: "4–16 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/e8a5629e6d7036422ee0cfa20261579d24a8f295.jpg",
    category: "Ходова частина",
    details: ["Листові та пневматичні підвіски", "Заміна втулок, амортизаторів", "Рихтування опорних кронштейнів", "Перевірка геометрії після ремонту"],
  },
  {
    slug: "comp-diagnostic",
    title: "Ремонт електрообладнання",
    short: "Діагностика та ремонт електрообладнання, стартерів, генераторів.",
    description:
      "Виконуємо діагностику та ремонт електрообладнання вантажних автомобілів, причепів і пов'язаних електросистем із застосуванням спеціалізованого обладнання.",
    price: "від 360 грн",
    priceMin: 360,
    priceMax: 3000,
    hours: "3–15 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/40d66fdf99f228ba1c28422090f83acaea02c970.jpg",
    category: "Електрика",
    details: ["Пошук обривів і коротких замикань", "Ремонт стартерів і генераторів", "Монтаж додаткового обладнання", "Перевірка бортової мережі"],
  },
  {
    slug: "comp-diagnostic-electro",
    title: "Комп'ютерна діагностика AutoCom",
    short: "Зчитування та скидання помилок, перевірка CAN-шини сканером AutoCom.",
    description:
      "Проводимо комп'ютерну діагностику електричних систем автомобілів і причепів за допомогою діагностичного сканера AutoCom для точного виявлення несправностей.",
    price: "від 240 грн",
    priceMin: 240,
    priceMax: 600,
    hours: "2–3 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/ed36e7694584bb9fb76bcf1a8ec9113cdf9ca1f7.jpg",
    category: "Діагностика",
    details: ["Сканер AutoCom", "Зчитування та скидання помилок", "Перевірка CAN-шини", "Детальний звіт після діагностики"],
  },
  {
    slug: "pc-diagnostic-trommelberg",
    title: "Діагностика розвалу-сходження Trommelberg",
    short: "Комп'ютерна діагностика і регулювання кутів на стенді Trommelberg.",
    description:
      "Проводимо комп'ютерну діагностику розвалу-сходження всіх марок автомобілів на діагностичному стенді Trommelberg.",
    price: "від 360 грн",
    priceMin: 360,
    priceMax: 800,
    hours: "3–4 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/14c3a40c51eeb0f15a66e5c4d7e3637b62c26c7b.jpg",
    category: "Діагностика",
    details: ["Стенд Trommelberg", "Усі марки авто", "Регулювання кутів після перевірки", "Рекомендовано після ремонту підвіски"],
  },
  {
    slug: "ecas",
    title: "Діагностика і калібрування пневмопідвіски ECAS",
    short: "Комп'ютерна діагностика і калібрування ECAS під навантаженням.",
    description:
      "Виконуємо комп'ютерну діагностику і калібрування пневмопідвіски з електронним керуванням ECAS для коректної роботи системи під навантаженням.",
    price: "від 480 грн",
    priceMin: 480,
    priceMax: 2000,
    hours: "4–10 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/b06a6716fffc58971cf31faf05e62f2923e9a829.jpg",
    category: "Пневмосистема",
    details: ["Електронне керування ECAS", "Калібрування висоти кузова", "Перевірка клапанів і сенсорів", "Налаштування під навантаження"],
  },
  {
    slug: "wabcohaldex",
    title: "Діагностика і ремонт WABCO і HALDEX",
    short: "Оригінальне ПЗ WABCO/HALDEX — точна діагностика та ремонт.",
    description:
      "Проводимо діагностику та ремонт систем WABCO і HALDEX оригінальним обладнанням для точного визначення несправностей.",
    price: "від 360 грн",
    priceMin: 360,
    priceMax: 2400,
    hours: "3–12 год",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop",
    category: "Гальмівна система",
    details: ["Оригінальне ПЗ WABCO/HALDEX", "Зчитування кодів помилок", "Ремонт модуляторів і клапанів", "Перевірка ефективності гальмування"],
  },
  {
    slug: "volvo-rvi",
    title: "Діагностика VOLVO і RVI комплексом VOCOM",
    short: "Оригінальна діагностика VOLVO FH/FM та RVI комплексом VOCOM.",
    description:
      "Проводимо комп'ютерну діагностику VOLVO і RVI оригінальним діагностичним комплексом VOCOM для точного зчитування помилок і параметрів.",
    price: "від 240 грн",
    priceMin: 240,
    priceMax: 600,
    hours: "2–3 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/2b10e63c94d90664b7587d2f543d5f8523a5b782.jpg",
    category: "Діагностика",
    details: ["Оригінальний комплекс VOCOM", "VOLVO FH, FM, FMX, FL, FE", "RVI / Renault Trucks", "Повна перевірка всіх систем"],
  },
  {
    slug: "adblue",
    title: "Роботи із системою AdBlue",
    short: "Програмне налаштування ЕБУ, роботи із системою AdBlue.",
    description:
      "Виконуємо роботи, пов'язані із системою AdBlue, залежно від конфігурації транспортного засобу та технічного стану авто.",
    price: "від 600 грн",
    priceMin: 600,
    priceMax: 2000,
    hours: "5–10 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/8daee9beb5e07ab91c97ad77d6dc174ce24ecbc7.jpg",
    category: "Електронні системи",
    details: ["Аналіз конфігурації авто", "Програмне налаштування ЕБУ", "Перевірка після втручання", "Без фізичного демонтажу деталей"],
  },
  {
    slug: "abs-ebs",
    title: "Діагностика і ремонт ABS і EBS",
    short: "Ремонт систем ABS/EBS, перевірка датчиків, модуляторів тиску.",
    description:
      "Проводимо діагностику і ремонт гальмівних систем ABS і EBS для безпечної експлуатації автомобіля та коректної роботи електронних компонентів.",
    price: "від 480 грн",
    priceMin: 480,
    priceMax: 2400,
    hours: "4–12 год",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&auto=format&fit=crop",
    category: "Гальмівна система",
    details: ["Електронне гальмування EBS", "Антиблокувальна система ABS", "Перевірка датчиків швидкості", "Ремонт модуляторів тиску"],
  },
  {
    slug: "remont-pnevmosistem",
    title: "Діагностика і ремонт пневматичної системи",
    short: "Пошук витоків, заміна клапанів, ремонт компресора пневмосистеми.",
    description:
      "Проводимо діагностику і ремонт пневматичної системи вантажного транспорту, забезпечуючи стабільну роботу вузлів пневмопідвіски та гальмування.",
    price: "від 360 грн",
    priceMin: 360,
    priceMax: 2400,
    hours: "3–12 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/0fa10922b0bc4e9125e79d6d96568277a3ec3dbd.jpg",
    category: "Пневмосистема",
    details: ["Пневматика гальм і підвіски", "Пошук витоків повітря", "Заміна клапанів і трубок", "Перевірка компресора"],
  },
  {
    slug: "zvaryuvalni-roboty",
    title: "Зварні роботи",
    short: "MIG/MAG зварювання рами, кронштейнів, підсилювачів конструкції.",
    description:
      "Виконуємо зварні роботи для вантажних автомобілів, причепів і окремих елементів конструкції з урахуванням експлуатаційних навантажень.",
    price: "від 480 грн",
    priceMin: 480,
    priceMax: 4000,
    hours: "4–20 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/e8a5629e6d7036422ee0cfa20261579d24a8f295.jpg",
    category: "Відновлювальні роботи",
    details: ["MIG/MAG зварювання", "Рама, кронштейни, підсилювачі", "Контроль зварних швів", "Підготовка поверхні перед зварюванням"],
  },
  {
    slug: "restavraciya-balok",
    title: "Реставрація балок і несучих елементів",
    short: "Наплавлення та механічна обробка балок до заводських допусків.",
    description:
      "Проводимо реставрацію балок із оцінкою стану, підбором способу відновлення та контролем якості виконаних робіт.",
    price: "від 1200 грн",
    priceMin: 1200,
    priceMax: 6000,
    hours: "10–30 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/98afea8526d7957b5b407040e0373b0e62216e98.jpg",
    category: "Відновлювальні роботи",
    details: ["Балки передніх і задніх мостів", "Оцінка ступеня зносу", "Наплавлення та механічна обробка", "Відновлення до заводських допусків"],
  },
  {
    slug: "restavracijni-roboty",
    title: "Реставрація гальмівних валів і кронштейнів",
    short: "Відновлення гальмівних валів, кронштейнів замість повної заміни.",
    description:
      "Виконуємо реставрацію гальмівних валів, кронштейнів підвіски та інших елементів, що потребують відновлення замість повної заміни.",
    price: "від 720 грн",
    priceMin: 720,
    priceMax: 3000,
    hours: "6–15 год",
    image: "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/4b96506b9c1e24cef4e01a1a1bc5f506be36f486.jpg",
    category: "Відновлювальні роботи",
    details: ["Гальмівні вали S-подібного типу", "Кронштейни ресорної підвіски", "Відновлення посадкових місць", "Дешевша альтернатива заміні"],
  },
];
